FROM sharelatex/sharelatex

RUN tlmgr update --self
RUN tlmgr install paralist
RUN tlmgr install csvsimple
RUN tlmgr install pgf
RUN tlmgr install etoolbox
RUN tlmgr install fancyvrb
RUN tlmgr install gobble
RUN tlmgr install xstring
RUN tlmgr install markdown
